NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
baltimore<-subset(NEI, NEI$fips==24510) 
baltimoreyeartotals <- tapply(baltimore$Emissions, baltimore$year, sum)
png("plot2.png")
barplot(baltimoreyeartotals, main = "Total PM2.5 Emissions by Year", xlab="Year", ylab="Emissions", col="navy")
dev.off()